apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aks-periscope-dev

bases:
- ../../base

patches:
- target:
    group: apps
    kind: DaemonSet
    name: aks-periscope
    version: v1
  patch: |-
    - op: replace
      path: '/spec/template/spec/containers/0/imagePullPolicy'
      value: Always

images:
- name: periscope-linux
  newName: loggeracr.azurecr.io/periscope-local
  newTag: v0.4.0
- name: periscope-windows
  newName: mcr.microsoft.com/aks/periscope-win
  newTag: latest

secretGenerator:
- name: azureblob-secret
  behavior: replace
  envs:
  - .env.secret

configMapGenerator:
- name: diagnostic-config
  behavior: merge
  envs:
  - .env.config
