# This is a basic workflow to help you get started with Actions
name: Building and Pushing to GHCR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, windows-2022]
        include:
        - os: ubuntu-latest
          file: ./builder/Dockerfile.linux
          imagename: 'aks/periscope'
        - os: windows-2022
          file: ./builder/Dockerfile.windows
          imagename: 'aks/periscope-win'
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v2
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_depth: 10
          path: ./CHANGELOG.md
      - name: Display output
        run: |
          echo "Version: ${{ steps.changelog_reader.outputs.version }}"
          echo "Changes: ${{ steps.changelog_reader.outputs.changes }}"
      # Lowercase my github ownername.
      - name: Set Environment Variables
        run: |
          $owner="${{ github.repository_owner }}".ToLower()
          echo "REPO-OWNER=$owner" >> $GITHUB_ENV
      - name: Login to GitHub Packages OCI Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to ghcr.io 
      # Note the below automatically sets the registry to the local GH registry of the org name. 
      # Currently, for pure gitops reconstructing this runtime setting will require looking at the repository owner of the commit
        run: |
          docker build -f ${{ matrix.file }} -t ghcr.io/${{ env.REPO-OWNER }}/${{ matrix.imagename }}:${{ steps.changelog_reader.outputs.version }} .
          docker push ghcr.io/${{ env.REPO-OWNER }}/${{ matrix.imagename }}:${{ steps.changelog_reader.outputs.version }}
