# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request for master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: 'Install OS Packages'
        run: |
          sudo apt update
          sudo apt --fix-broken install -y
          sudo apt install python3-pip -y
          pip3 install setuptools
          pip3 install pylint coverage
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.40.1
 
      - name: Start kind
        run: bash -f ./azurepipeline/start.sh --kind-cluster-name=integrationtest
        continue-on-error: false

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build project
        run: go build -v ./cmd/aks-periscope/aks-periscope.go

      - name: Run integration test
        run: go test -v -mod=mod ./tests/aksperiscopeintegration_test.go

      - name: Check go linter
        run: golangci-lint run
        continue-on-error: false

      - name: Stop kind
        run: bash -f ./azurepipeline/stop.sh --kind-cluster-name=integrationtest
        continue-on-error: false